name: Unit tests

on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'utest/**'
      - '!**/*.rst'


jobs:
  test_using_builtin_python:

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        python-version: ['3.11']
        exclude:
          - os: windows-latest
            python-version: 'pypy-3.8'

    runs-on: ${{ matrix.os }}

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Run unit tests with coverage
        run: |
          python -m pip install coverage
          python -m pip install -r utest/requirements.txt
          python -m coverage run --branch utest/run.py -v

      - name: Prepare HTML/XML coverage report
        run: |
          python -m coverage xml -i
        if: always()

      - uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2
        with:
          name: ${{ matrix.python-version }}-${{ matrix.os }}
        if: always()
